export const PRODUCTS_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCTS_DETAILS_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCT_LIST_FAIL'