const data = {
    produts:[
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1/jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}